import React, { useState } from "react";
import { Modal, Button, Form, Col, Alert } from "react-bootstrap";

const NewOfficeModal = (props) => {
  const [fields, setFields] = useState({
    firstName: "",
    lastName: "",
    email: "",
    roomNumber: "",
    building: "",
    street: "",
    city: "",
    province: "",
  });
  const [alertContent, setAlertContent] = useState({
    content: "",
    show: false,
    variant: "danger",
  });

  const onChange = (e) => {
    setFields({ ...fields, [e.target.name]: e.target.value });
  };

  const onClickSubmit = (e) => {
    let token = localStorage.getItem("auth-token");
    setAlertContent({
      content: "",
      show: false,
      variant: "danger",
    });

    //verify if the fields are empty
    if (
      fields.email === "" ||
      fields.firstName === "" ||
      fields.lastName === "" ||
      fields.street === "" ||
      fields.city === "" ||
      fields.province === "" ||
      fields.roomNumber === "" ||
      fields.building === ""
    ) {
      setAlertContent({
        show: true,
        content: "All fields required!",
        variant: "danger",
      });
    } else {
      try {
        fetch("/api/admin/registerOffice", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-auth-token": token,
          },
          body: JSON.stringify(fields),
        })
          .then((response) => {
            return response.json();
          })
          .then((data) => {
            if (data.msgError) {
              setAlertContent({
                content: data.msg.body,
                show: true,
                variant: "danger",
              });
            } else {
              setAlertContent({
                content: data.msg.body,
                show: true,
                variant: "success",
              });
              setTimeout(() => {
                props.toggle();
                props.reloadList();
              }, 3000);
            }
          });
      } catch (err) {
        setAlertContent({
          content: err.msg,
          show: true,
          variant: "danger",
        });
      }
    }
  };

  return (
    <Modal show={props.show} className="p-3" backdrop="static">
      <Modal.Header>Create New Office Account</Modal.Header>
      <Modal.Body>
        <Form>
          <Form.Row>
            <Col>
              <Form.Group>
                <Form.Label>First Name</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Juan"
                  onChange={onChange}
                  value={fields.firstName}
                  name="firstName"
                />
              </Form.Group>
            </Col>
            <Col>
              <Form.Group>
                <Form.Label>Last Name</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Dela Cruz"
                  onChange={onChange}
                  value={fields.lastName}
                  name="lastName"
                />
              </Form.Group>
            </Col>
          </Form.Row>

          <Form.Row>
            <Col>
              <Form.Group>
                <Form.Label>Email address</Form.Label>

                <Form.Control
                  type="email"
                  placeholder="Enter email"
                  onChange={onChange}
                  value={fields.email}
                  name="email"
                />
                <Form.Text className="text-muted">
                  An autogenerated password will be sent to the email provided.
                </Form.Text>
              </Form.Group>
            </Col>
          </Form.Row>

          <Form.Row>
            <Col md={2} lg={2} sm={2} xs={2}>
              <Form.Group>
                <Form.Label>Rm. #</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="101"
                  onChange={onChange}
                  value={fields.roomNumber}
                  name="roomNumber"
                />
              </Form.Group>
            </Col>

            <Col>
              <Form.Group>
                <Form.Label>Building</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Main Building"
                  onChange={onChange}
                  value={fields.building}
                  name="building"
                />
              </Form.Group>
            </Col>

            <Col>
              <Form.Group>
                <Form.Label>Street Address</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="101 Rizal street"
                  onChange={onChange}
                  value={fields.street}
                  name="street"
                />
              </Form.Group>
            </Col>
          </Form.Row>
          <Form.Row>
            <Col>
              <Form.Group>
                <Form.Label>City</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Dagupan"
                  onChange={onChange}
                  value={fields.city}
                  name="city"
                />
              </Form.Group>
            </Col>
            <Col>
              <Form.Group>
                <Form.Label>Province</Form.Label>
                <Form.Control
                  type="text"
                  placeholder="Pangasinan"
                  onChange={onChange}
                  value={fields.province}
                  name="province"
                />
              </Form.Group>
            </Col>
          </Form.Row>
        </Form>
        <Alert show={alertContent.show} variant={alertContent.variant}>
          {alertContent.content}
        </Alert>
      </Modal.Body>
      <Modal.Footer>
        <Button variant="secondary" onClick={props.toggle}>
          Close
        </Button>
        <Button variant="primary" onClick={onClickSubmit}>
          Set Appointment
        </Button>
      </Modal.Footer>
    </Modal>
  );
};
export default NewOfficeModal;
